name: Build and Test

on:
  push:
    branches: [master, ci-test]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ['ubuntu:22.04', 'ubuntu:24.04', 'archlinux:base-devel']

    container:
      image: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-ubuntu
        if: ${{ startsWith(matrix.container, 'ubuntu') }}
      - uses: ./.github/actions/setup-archlinux
        if: ${{ startsWith(matrix.container, 'archlinux') }}

      - name: configure
        run: |
          mkdir build
          cd build
          ../autogen.sh c

      - name: build
        run: |
          cd build
          make -j$(nproc)

      - name: test
        run: |
          cd build
          make KDIR=/usr/lib/modules/*/build -j$(nproc) check

      - name: install
        run: |
          cd build
          DESTDIR=$PWD/inst make install

      - name: distcheck
        run: |
          cd build
          make KDIR=/usr/lib/modules/*/build distcheck
